Add multi-cloud user guide
sodafoundation/documentation pull request #101
Opened 2020-09-15 08:45 UTC by rajat-soda

**What type of PR is this?**

> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
/kind documentation

**What this PR does / why we need it**:
The PR adds multi-cloud documentation in the User Guides Section

**Which issue(s) this PR fixes**:

Fixes #1072 multi-cloud issue

**Test Report Added?**:
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
> /kind TESTED

**Test Report**:

![image](https://user-images.githubusercontent.com/65751939/93187836-da04fa80-f75d-11ea-8715-13688ebc95a2.png)

**Special notes for your reviewer**:

2020-09-15 08:47 UTC, rajat-soda commented
@kumarashit  @anvithks  Please review and merge

2020-09-15 10:08 UTC, anvithks reviewed
I think this is more of a developer guide a we are providing instructions to install from source and bring up Multi-cloud alone to setup an environment for development. 
@kumarashit @himanshuvar Please take a look.

2020-09-15 10:52 UTC, rajat-soda commented
> I think this is more of a developer guide a we are providing instructions to install from source and bring up Multi-cloud alone to setup an environment for development.
> @kumarashit @himanshuvar Please take a look.

moved multi-cloud dev guide to Developer Guide Section

2020-09-16 18:25 UTC, kumarashit requested changes

2020-09-16 18:25 UTC, kumarashit commented on content/guides/developer-guides/object-lifecycle-management/_index.md
> +This guide is intended for Object Lifecycle feature developers. It provides detailed steps to write new API using SODA. To understand the feature and requirements in detail, please refer to the Objec
```suggestion
This guide is intended for Object Lifecycle feature developers. It provides detailed steps to write new API using SODA. To understand the feature and requirements in detail, please refer to the Object Lifecycle Management [user guide](/guides/user-guides/object-lifecycle-management/) and Object Lifecycle [design spec](https://github.com/sodafoundation/design-specs/blob/master/specs/capri/object_lifecycle_management.md). 
```

2020-09-16 18:25 UTC, kumarashit commented on content/guides/developer-guides/object-lifecycle-management/_index.md
> +    a) All APIs go into the 's3' module of the SODA multi-cloud package, i,e. opensds/multi-cloud/api/pkg/s3 directory
```suggestion
    a) All APIs go into the 's3' module of the SODA multi-cloud package, i,e. sodafoundation/multi-cloud/api/pkg/s3 directory
```

2020-09-16 18:25 UTC, kumarashit commented on content/guides/developer-guides/object-lifecycle-management/_index.md
> +    a) All APIs goes into the 's3' module of the SODA multi-cloud package, i,e. opensds/multi-cloud/api/pkg/s3 directory
```suggestion
    a) All APIs goes into the 's3' module of the SODA multi-cloud package, i,e. sodafoundation/multi-cloud/api/pkg/s3 directory
```

2020-09-16 18:25 UTC, kumarashit commented on content/guides/user-guides/object-lifecycle-management/_index.md
>  git clone https://github.com/opensds/opensds-installer.git
```suggestion
git clone https://github.com/sodafoundation/installer.git
```

2020-09-16 18:25 UTC, kumarashit commented on content/guides/user-guides/orchestration/_index.md
>  Please refer to this guide or release notes first for any known issues or workarounds available. Issues related to Orchestration can be raised at https://github.com/opensds/orchestration/issues
```suggestion
Please refer to this guide or release notes first for any known issues or workarounds available. Issues related to Orchestration can be raised at https://github.com/sodafoundation/orchestration/issues
```

2020-09-16 18:25 UTC, kumarashit commented on content/guides/user-guides/orchestration/_index.md
> +Please refer https://github.com/opensds/orchestration/blob/master/docs/INSTALL.md to install SODA and all the required components of Orchestration.
```suggestion
Please refer https://github.com/sodafoundation/orchestration/blob/master/docs/INSTALL.md to install SODA and all the required components of Orchestration.
```

2020-09-16 18:25 UTC, kumarashit commented on content/guides/user-guides/orchestration/_index.md
> +* Deploy SODA (https://github.com/opensds/opensds/wiki)
can we provide the link to docs.sodafoundation. we are going to phase out wiki

2020-09-16 18:25 UTC, kumarashit commented on content/guides/user-guides/orchestration/_index.md
> +* Deploy StackStorm with [SODA packs](https://github.com/opensds/orchestration/blob/master/docs/INSTALL.md)
```suggestion
* Deploy StackStorm with [SODA packs](https://github.com/sodafoundation/orchestration/blob/master/docs/INSTALL.md)
```

2020-09-17 04:13 UTC, merged

2020-09-17 04:14 UTC, kumarashit reviewed
LGTM