Updated the commands of installing multi-cloud server
sodafoundation/documentation pull request #198
Opened 2022-03-30 14:50 UTC by shelar1423

issue: #195 

- Updated the commands of installing multi-cloud server After mkdir command a cd command  added where we will clone the multi-cloud repo.
 
#sodacode2022
#sodalow 
regards 
your contributor
Digvijay shelar 
@shelar1423

2022-03-30 14:52 UTC, shelar1423 commented
@skdwriting  kindly label sodalow and sodacode2022

2022-04-06 11:29 UTC, anvithks requested changes
Please check the review comments. Either of the solutions will work.

2022-04-06 11:29 UTC, anvithks commented on content/guides/developer-guides/multi-cloud/_index.md
> +mkdir cd -p /root/gopath/src/github.com/sodafoundation/
What does this command do? We already use mkdir with the -p option to create the directory structure.
The correct way would be to provide the path in the clone command as :  
`git clone https://github.com/sodafoundation/multi-cloud.git /root/gopath/src/github.com/sodafoundation/`

or  

Change the order of the commands. Navigate to the `/root/gopath/src/github.com/sodafoundation/` folder first and then clone.

2022-04-06 11:29 UTC, anvithks commented on content/guides/developer-guides/multi-cloud/_index.md
> +```
What is changed here?

2022-04-06 12:08 UTC, shelar1423 commented
> Please check the review comments. Either of the solutions will work.

Made changes according to your comments have a look

2022-05-01 06:31 UTC, anvithks commented
@shelar1423 this is a duplicate of #197

2023-10-13 20:23 UTC, closed without merging