Document update for Nevarino release
sodafoundation/documentation pull request #268
Opened 2022-12-09 11:23 UTC by amanr032

What type of PR is this?

> /kind documentation

What this PR does / why we need it:
 Documentation for the change of installation steps 

Which issue(s) this PR fixes:
Fixes 

Test Report Added?:
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
> /kind TESTED
> /kind NOT-TESTED

Test Report:

2022-12-13 06:29 UTC, anvithks requested changes
Please check the review comments.

2022-12-13 06:29 UTC, anvithks commented on content/soda-gettingstarted/quickstart.md
> +This procedure applies to 18.04 & 20.04 Linux distributions.
Ubuntu 18.04 & 20.04

2022-12-13 06:29 UTC, anvithks commented on content/soda-gettingstarted/quickstart.md
> +     Enable following configurations
This only enables delfin. What about Multicloud and Terra?

2022-12-13 06:29 UTC, anvithks commented on content/soda-gettingstarted/quickstart.md
> +**_NOTE:_**  The note content.Please replace RELEASE_TAG with the corresponding value from Release Tag table above (ex: v1.8.0 etc)
Use the notice shortcode.

2022-12-13 06:45 UTC, anvithks commented on content/soda-gettingstarted/quickstart.md
> +wget  [https://github.com/sodafoundation/installer/releases/download/<RELEASE_TAG>/installer-[RELEASE_TAG].tar.gz](https://github.com/sodafoundation/installer/releases/download/[RELEASE_TAG]/installe
Change the Markdown URL format to simple URL [https://github.com/sodafoundation/installer/releases/download/<RELEASE_TAG>/installer-[RELEASE_TAG].tar.gz](https://github.com/sodafoundation/installer/releases/download/[RELEASE_TAG]/installer-[RELEASE_TAG].tar.gz) - > https://github.com/sodafoundation/installer/releases/download/[RELEASE_TAG]/installer-[RELEASE_TAG].tar.gz

2022-12-14 05:28 UTC, anvithks submitted a review, later dismissed
LGTM

2022-12-14 05:29 UTC, joseph-v commented on content/soda-gettingstarted/quickstart.md
> +	- **Terra**
```suggestion
	- **Terra (SODA Hotpot)**  
```

2022-12-14 05:36 UTC, amanr032 commented on content/soda-gettingstarted/quickstart.md
> +	- **Terra**
updated

2022-12-14 06:46 UTC, joseph-v submitted a review, later dismissed
LGTM

2022-12-15 06:07 UTC, anvithks submitted a review, later dismissed
Some minor nits. Please fix the review comments and then merge the PR.
LGTM

2022-12-15 06:07 UTC, anvithks commented on content/soda-gettingstarted/quickstart.md
> +- **Enable configurations to install Soda Products**
nit: Soda -> SODA

2022-12-15 06:07 UTC, anvithks commented on content/soda-gettingstarted/quickstart.md
> +	- **STRATO (SODA MultiCloud)**
nit: MultiCloud -> Multicloud

2022-12-15 07:14 UTC, amanr032 commented on content/soda-gettingstarted/quickstart.md
> +- **Enable configurations to install Soda Products**
updated

2022-12-15 07:15 UTC, amanr032 commented on content/soda-gettingstarted/quickstart.md
> +	- **STRATO (SODA MultiCloud)**
updated

2022-12-15 07:47 UTC, anvithks approved these changes
LGTM

2022-12-19 03:30 UTC, joseph-v approved these changes
LGTM

2022-12-19 03:30 UTC, merged