[WIP] [TUTORIAL] How to setup VS Code environment for Angular development.
sodafoundation/documentation pull request #302
Opened 2023-04-13 05:25 UTC by Megatron482

Documentation on VS Code

2023-04-14 04:15 UTC, anvithks requested changes
@Megatron482 @Deepikavk00 Overall looks good.
Please check the review comments.
Also use the heading tags only for main section headings. The rest of the text can be in normal font.

2023-04-14 04:15 UTC, anvithks commented on learning/dashboard/Group-5/OPSG5.md
> +## 4. After the VS Code has finsihed downloading go through the setup process by clicking next and wait for it to download.
typo: finsihed -> finished

2023-04-14 04:15 UTC, anvithks commented on learning/dashboard/Group-5/OPSG5.md
> +![image](https://user-images.githubusercontent.com/123230201/227721915-a0e28d2c-f0ca-44a8-98cb-f3a7df7318ab.png)
Consider adding some information about the Angular Snippets extension. 
How can one use it? 
Some examples

2023-04-14 04:15 UTC, anvithks commented on learning/dashboard/Group-5/OPSG5.md
> +![image](https://user-images.githubusercontent.com/123230201/227722349-5c408e0e-188e-40fc-8cd1-08530beeac9a.png) <p>
Consider adding some information about the JSLint extension.
What is the usage and how it helps users.

2023-04-14 04:15 UTC, anvithks commented on learning/dashboard/Group-5/OPSG5.md
> +![image](https://user-images.githubusercontent.com/123230201/227724297-64c61345-83e1-4e33-a7b9-0ee8a7f4a8b2.png)
Consider adding some more information regarding the JSON extension.

2023-04-14 04:15 UTC, anvithks commented on learning/dashboard/Group-5/OPSG5.md
> +![image](https://user-images.githubusercontent.com/123230201/227724718-2e98ef5c-9d77-4c27-b256-dd16b9b5c71a.png)
Consider adding usage instructions and how it helps.

2023-04-14 04:15 UTC, anvithks commented on learning/dashboard/Group-5/OPSG5.md
> +## 2. Type Prettifier extension and click on the third option and click install and wait for it to install.
This seems to be the incorrect Prettifier extension. This one is downloaded some 123 times.
The correct prettifier extension is downloaded many more times.
Consider adding some usage instructions and how it helps.

2023-06-17 16:45 UTC, wasup-yash commented on learning/dashboard/Group-5/OPSG5.md
> +#
Could remove this Line 24

2025-05-20 20:23 UTC, closed without merging